# MODE="LIVE|QA|BUILD" LATEST_TAG=$(git describe --tags --abbrev=0) docker compose up --build
services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    image: datajoint-python-docs
    environment:
      - MODE
      - LATEST_TAG
    volumes:
      - ..:/main
    ports:
      - 8000:8000
    command:
      - sh
      - -c
      - |
        set -e
        if echo "$${MODE}" | grep -i live &>/dev/null; then
            mkdocs serve --config-file mkdocs.yaml -a 0.0.0.0:8000
        elif echo "$${MODE}" | grep -iE "qa|build" &>/dev/null; then
            git branch -D gh-pages || true
            git fetch $${UPSTREAM_REPO} gh-pages:gh-pages || true
            mike deploy --config-file mkdocs.yaml -u $$LATEST_TAG latest
            mike set-default --config-file mkdocs.yaml latest
            if echo "$${MODE}" | grep -i qa &>/dev/null; then
                mike serve --config-file mkdocs.yaml -a 0.0.0.0:8000
            fi
        else
            echo "Unexpected mode..."
            exit 1
        fi
