name: Docs release
on:
  # manually trigger
  workflow_dispatch:
  # Once draft release is released, trigger the docs release
  release:
    types:
      ## pre-release and stable release
      #- published
      ## stable release only
      - released
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy docs
        run: |
          export MODE=BUILD
          export PACKAGE=datajoint
          export UPSTREAM_REPO=https://github.com/${GITHUB_REPOSITORY}.git
          export HOST_UID=$(id -u)
          docker compose -f docs/docker-compose.yaml up --exit-code-from docs --build
          git push origin gh-pages
